<?php

function acf_featured_buttons()
{
    return array(
        array(
            'key' => 'field_5f5a27d7acd8b',
            'label' => 'Featured Buttons',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_61847ce9ce3dz',
            'label' => 'Featured Buttons Title',
            'name' => 'featured_buttons_title',
            'type' => 'text',
            'instructions' => 'Character limit 50.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => 50,
        ),
        array(
            'key' => 'field_5f5a27feacd8c',
            'label' => 'Featured Buttons',
            'name' => 'featured_buttons',
            'type' => 'repeater',
            'instructions' => 'These buttons will display just below the Hero.<br />*Max: 8',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => 'field_60ff03abcbe83',
            'min' => 2,
            'max' => 8,
            'layout' => 'block',
            'button_label' => 'Add Featured Button',
            'sub_fields' => array(
                array(
                    'key' => 'field_60ff0354cbe82',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_60ff03abcbe83',
                    'label' => 'Link',
                    'name' => 'link',
                    'type' => 'link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                ),
            ),
        ),
    );
}