<?php if( function_exists('acf_add_local_field_group') ):
acf_add_local_field_group(array(
	'key' => 'group_5e7cae3363c0z',
	'title' => 'Homepage',
	'fields' => array(
		array(
			'key' => 'field_5f5f70a43c445',
			'label' => 'Hero',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5e7cae3375f91',
			'label' => 'Hero Overlay',
			'name' => 'hero_overlay',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				0 => 'No Overlay',
				'0.125' => 'Extra Light Overlay',
				'0.25' => 'Light Overlay',
				'0.5' => 'Medium Overlay',
				'0.75' => 'Heavy Overlay',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_6124f4ba89662',
			'label' => 'Parallax Scrolling',
			'name' => 'hero_parallax',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5e7cae336b5e8',
			'label' => 'Hero Type',
			'name' => 'is_video',
			'type' => 'true_false',
			'instructions' => 'This section is shown at the top of the Homepage.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Video',
			'ui_off_text' => 'Image',
		),
		array(
			'key' => 'field_5e7cae3367ff3',
			'label' => 'Slider: Image',
			'name' => 'slider_image',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e7cae336b5e8',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '75',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 1,
			'max' => 6,
			'layout' => 'block',
			'button_label' => 'Add Slide',
			'sub_fields' => array(
				array(
					'key' => 'field_60ff12b219e39',
					'label' => 'Image',
					'name' => 'hero_slider_image',
					'type' => 'image',
					'instructions' => 'Recommended size 1650x900.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_60ff12c219e3a',
					'label' => 'Title',
					'name' => 'title',
					'type' => 'text',
					'instructions' => 'Max Characters: 70',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => 70,
				),
				array(
					'key' => 'field_60ff12cd19e3z',
					'label' => 'Text',
					'name' => 'text',
					'type' => 'text',
					'instructions' => 'Max Characters: 30',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => 30,
				),
				// array(
				// 	'key' => 'field_60ff12cd19e3b',
				// 	'label' => 'Links',
				// 	'name' => 'links',
				// 	'type' => 'repeater',
				// 	'instructions' => '',
				// 	'required' => 0,
				// 	'conditional_logic' => 0,
				// 	'wrapper' => array(
				// 		'width' => '',
				// 		'class' => '',
				// 		'id' => '',
				// 	),
				// 	'collapsed' => '',
				// 	'min' => 0,
				// 	'max' => 2,
				// 	'layout' => 'table',
				// 	'button_label' => '',
				// 	'sub_fields' => array(
				// 		array(
				// 			'key' => 'field_60ff12e019e3c',
				// 			'label' => 'Link',
				// 			'name' => 'link',
				// 			'type' => 'link',
				// 			'instructions' => '',
				// 			'required' => 0,
				// 			'conditional_logic' => 0,
				// 			'wrapper' => array(
				// 				'width' => '',
				// 				'class' => '',
				// 				'id' => '',
				// 			),
				// 			'return_format' => 'array',
				// 		),
				// 		array(
				// 			'key' => 'field_61098cd8e212a',
				// 			'label' => 'Background Color',
				// 			'name' => 'hero_button_background_color',
				// 			'type' => 'select',
				// 			'instructions' => '',
				// 			'required' => 0,
				// 			'conditional_logic' => 0,
				// 			'wrapper' => array(
				// 				'width' => '',
				// 				'class' => '',
				// 				'id' => '',
				// 			),
				// 			'choices' => array(
				// 				'primary' => 'Primary',
				// 				'transparent' => 'Transparent',
				// 			),
				// 			'default_value' => false,
				// 			'allow_null' => 0,
				// 			'multiple' => 0,
				// 			'ui' => 0,
				// 			'return_format' => 'value',
				// 			'ajax' => 0,
				// 			'placeholder' => '',
				// 		),
				// 	),
				// ),
			),
		),
		array(
			'key' => 'field_5f5a50cf7309c',
			'label' => 'Slider: Video',
			'name' => 'slider_video',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e7cae336b5e8',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '75',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_612ecc6e792c0',
					'label' => 'Poster Image',
					'name' => 'poster_image',
					'type' => 'image',
					'instructions' => '*optional, shows while video is loading',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_612ed07f792c1',
					'label' => 'webm',
					'name' => 'webm',
					'type' => 'file',
					'instructions' => 'Video in webm format',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'webm',
				),
				array(
					'key' => 'field_612ed0a0792c2',
					'label' => 'mp4',
					'name' => 'mp4',
					'type' => 'file',
					'instructions' => 'Video in mp4 format',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '34',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'mp4',
				),
			),
		),
		array(
		'key' => 'field_626c37b2602a3',
		'label' => 'Parish Buttons',
		'name' => '',
		'type' => 'tab',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'placement' => 'top',
		'endpoint' => 0,
		),
		array(
			'key' => 'field_626c37cd602a4',
			'label' => 'Cluster Style',
			'name' => 'cluster_style',
			'aria-label' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'buttons' => 'Buttons',
				'scroll' => 'Scroll',
				'map' => 'Map',
			),
			'default_value' => '',
			'return_format' => 'value',
			'allow_null' => 0,
			'other_choice' => 0,
			'layout' => 'vertical',
			'save_other_choice' => 0,
		),
		 array(
		 	'key' => 'field_626c3734abd52',
		 	'label' => 'Parish Buttons',
		 	'name' => 'parish_buttons',
		 	'type' => 'repeater',
		 	'instructions' => '',
		 	'required' => 0,
		 	'conditional_logic' => array(
		 		array(
		 			array(
		 				'field' => 'field_626c37cd602a4',
		 				'operator' => '==',
		 				'value' => 'buttons',
		 			),
		 		),
		 	),
		 	'wrapper' => array(
		 		'width' => '',
		 		'class' => '',
		 		'id' => '',
		 	),
		 	'collapsed' => '',
		 	'min' => 0,
		 	'max' => 0,
		 	'layout' => 'table',
		 	'button_label' => '',
		 	'sub_fields' => array(
		 		array(
		 			'key' => 'field_626c3747abd53',
		 			'label' => 'Image',
		 			'name' => 'image',
		 			'type' => 'image',
		 			'instructions' => 'Recommended aspect ratio 370 / 305.',
		 			'required' => 0,
		 			'conditional_logic' => 0,
		 			'wrapper' => array(
		 				'width' => '',
		 				'class' => '',
		 				'id' => '',
		 			),
		 			'return_format' => 'url',
		 			'preview_size' => 'medium',
		 			'library' => 'all',
		 			'min_width' => '',
		 			'min_height' => '',
		 			'min_size' => '',
		 			'max_width' => '',
		 			'max_height' => '',
		 			'max_size' => '',
		 			'mime_types' => '',
		 		),
       			array(
       			'key' => 'field_626c3734abd5z',
       			'label' => 'Mass Times',
       			'name' => 'mass_times',
       			'type' => 'repeater',
       			'instructions' => 'Max Characters: 30',
       			'required' => 0,
       			'wrapper' => array(
       				'width' => '',
       				'class' => '',
       				'id' => '',
       			),
       			'collapsed' => '',
       			'min' => 0,
       			'max' => 3,
       			'layout' => 'table',
       			'button_label' => '',
       			'sub_fields' => array(
       				array(
       					'key' => 'field_626c3773abd54',
       					'label' => 'Time',
       					'name' => 'text',
       					'type' => 'text',
       					'instructions' => '',
       					'required' => 0,
       					'conditional_logic' => 0,
       					'wrapper' => array(
       						'width' => '',
       						'class' => '',
       						'id' => '',
       					),
       					'default_value' => '',
       					'placeholder' => '',
       					'maxlength' => 30,
       					'rows' => '',
       					'new_lines' => '',
       				),
		 	      ),
         		),
		 		array(
		 			'key' => 'field_626c3773abd5z',
		 			'label' => 'Title',
		 			'name' => 'title',
		 			'type' => 'text',
		 			'instructions' => 'Max Characters: 25',
		 			'required' => 0,
		 			'conditional_logic' => 0,
		 			'wrapper' => array(
		 				'width' => '',
		 				'class' => '',
		 				'id' => '',
		 			),
		 			'default_value' => '',
		 			'placeholder' => '',
		 			'maxlength' => 25,
		 			'rows' => '',
		 			'new_lines' => '',
		 		),
		 		array(
		 			'key' => 'field_626c379dabd55',
		 			'label' => 'Link',
		 			'name' => 'link',
		 			'type' => 'link',
		 			'instructions' => 'Please note the Title field will display instead of the link text.',
		 			'required' => 0,
		 			'conditional_logic' => 0,
		 			'wrapper' => array(
		 				'width' => '',
		 				'class' => '',
		 				'id' => '',
		 			),
		 			'return_format' => 'array',
		 		),
		 	),
		 ),
		 array(
		 	'key' => 'field_6270a5d99e494',
		 	'label' => 'Parish Scroll Title',
		 	'name' => 'parish_scroll_title',
		 	'type' => 'text',
		 	'instructions' => 'Max characters: 30',
		 	'required' => 0,
		 	'conditional_logic' => array(
		 		array(
		 			array(
		 				'field' => 'field_626c37cd602a4',
		 				'operator' => '!=',
		 				'value' => 'buttons',
		 			),
		 		),
		 	),
		 	'wrapper' => array(
		 		'width' => '',
		 		'class' => '',
		 		'id' => '',
		 	),
		 	'default_value' => '',
		 	'placeholder' => '',
		 	'prepend' => '',
		 	'append' => '',
		 	'maxlength' => 30,
		 ),
		 array(
			 'key' => 'field_65f19df8329d0',
			 'label' => 'Parishes',
			 'name' => 'parish_maps',
			 'aria-label' => '',
			 'type' => 'repeater',
			 'instructions' => '',
			 'required' => 0,
		 	'conditional_logic' => array(
		 		array(
		 			array(
		 				'field' => 'field_626c37cd602a4',
		 				'operator' => '==',
		 				'value' => 'map',
		 			),
		 		),
		 	),
			 'wrapper' => array(
				 'width' => '',
				 'class' => '',
				 'id' => '',
			 ),
			 'layout' => 'table',
			 'pagination' => 0,
			 'min' => 0,
			 'max' => 0,
			 'collapsed' => '',
			 'button_label' => 'Add Row',
			 'rows_per_page' => 20,
			 'sub_fields' => array(
				 array(
					 'key' => 'field_65f19e2a329d1',
					 'label' => 'Parish Name',
					 'name' => 'parish_name',
					 'aria-label' => '',
					 'type' => 'text',
					 'instructions' => '',
					 'required' => 0,
					 'conditional_logic' => 0,
					 'wrapper' => array(
						 'width' => '',
						 'class' => '',
						 'id' => '',
					 ),
					 'default_value' => '',
					 'maxlength' => '',
					 'placeholder' => '',
					 'prepend' => '',
					 'append' => '',
					 'parent_repeater' => 'field_65f19df8329d0',
				 ),
				array(
					'key' => 'field_626c379dabd5z',
					'label' => 'Link',
					'name' => 'link',
					'type' => 'link',
					'instructions' => 'Please note the Parish Name field will display instead of the link text.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
				 array(
					 'key' => 'field_65f19e4b329d2',
					 'label' => 'Address',
					 'name' => 'address',
					 'aria-label' => '',
					 'type' => 'text',
					 'instructions' => '',
					 'required' => 0,
					 'conditional_logic' => 0,
					 'wrapper' => array(
						 'width' => '',
						 'class' => '',
						 'id' => '',
					 ),
					 'default_value' => '',
					 'maxlength' => '',
					 'placeholder' => '',
					 'prepend' => '',
					 'append' => '',
					 'parent_repeater' => 'field_65f19df8329d0',
				 ),
				 array(
					 'key' => 'field_65f19e5b329d3',
					 'label' => 'Phone',
					 'name' => 'phone',
					 'aria-label' => '',
					 'type' => 'text',
					 'instructions' => '',
					 'required' => 0,
					 'conditional_logic' => 0,
					 'wrapper' => array(
						 'width' => '',
						 'class' => '',
						 'id' => '',
					 ),
					 'default_value' => '',
					 'maxlength' => '',
					 'placeholder' => '',
					 'prepend' => '',
					 'append' => '',
					 'parent_repeater' => 'field_65f19df8329d0',
				 ),
				 array(
					 'key' => 'field_65f19e6d329d5',
					 'label' => 'Email',
					 'name' => 'email',
					 'aria-label' => '',
					 'type' => 'text',
					 'instructions' => '',
					 'required' => 0,
					 'conditional_logic' => 0,
					 'wrapper' => array(
						 'width' => '',
						 'class' => '',
						 'id' => '',
					 ),
					 'default_value' => '',
					 'maxlength' => '',
					 'placeholder' => '',
					 'prepend' => '',
					 'append' => '',
					 'parent_repeater' => 'field_65f19df8329d0',
				 ),
				//  array(
				// 	 'key' => 'field_65f19e7b329d6',
				// 	 'label' => 'Map',
				// 	 'name' => 'map',
				// 	 'aria-label' => '',
				// 	 'type' => 'text',
				// 	 'instructions' => 'Paste contents of src from the iframe in "Embed a Map" on Google Maps.',
				// 	 'required' => 0,
				// 	 'conditional_logic' => 0,
				// 	 'wrapper' => array(
				// 		 'width' => '',
				// 		 'class' => '',
				// 		 'id' => '',
				// 	 ),
				// 	 'default_value' => '',
				// 	 'maxlength' => '',
				// 	 'placeholder' => '',
				// 	 'prepend' => '',
				// 	 'append' => '',
				// 	 'parent_repeater' => 'field_65f19df8329d0',
				//  ),
				 array(
					 'key' => 'field_65f19e6d329zz',
					 'label' => 'Latitude',
					 'name' => 'latitude',
					 'aria-label' => '',
					 'type' => 'text',
					 'instructions' => '',
					 'required' => 0,
					 'conditional_logic' => 0,
					 'wrapper' => array(
						 'width' => '',
						 'class' => '',
						 'id' => '',
					 ),
					 'default_value' => '',
					 'maxlength' => '',
					 'placeholder' => '',
					 'prepend' => '',
					 'append' => '',
					 'parent_repeater' => 'field_65f19df8329d0',
				 ),
				 array(
					 'key' => 'field_65f19e6d329zy',
					 'label' => 'Longitude',
					 'name' => 'longitude',
					 'aria-label' => '',
					 'type' => 'text',
					 'instructions' => '',
					 'required' => 0,
					 'conditional_logic' => 0,
					 'wrapper' => array(
						 'width' => '',
						 'class' => '',
						 'id' => '',
					 ),
					 'default_value' => '',
					 'maxlength' => '',
					 'placeholder' => '',
					 'prepend' => '',
					 'append' => '',
					 'parent_repeater' => 'field_65f19df8329d0',
				 ),
			 ),
		 ),
		 array(
		 	'key' => 'field_626c380e602a5',
		 	'label' => 'Parish Scroll',
		 	'name' => 'parish_scroll',
		 	'type' => 'repeater',
		 	'instructions' => '',
		 	'required' => 0,
		 	'conditional_logic' => array(
		 		array(
		 			array(
		 				'field' => 'field_626c37cd602a4',
		 				'operator' => '==',
		 				'value' => 'scroll',
		 			),
		 		),
		 	),
		 	'wrapper' => array(
		 		'width' => '',
		 		'class' => '',
		 		'id' => '',
		 	),
		 	'collapsed' => '',
		 	'min' => 0,
		 	'max' => 0,
		 	'layout' => 'table',
		 	'button_label' => '',
		 	'sub_fields' => array(
		 		array(
		 			'key' => 'field_626c3822602a6',
		 			'label' => 'Parish',
		 			'name' => 'parish',
		 			'type' => 'link',
		 			'instructions' => '',
		 			'required' => 0,
		 			'conditional_logic' => 0,
		 			'wrapper' => array(
		 				'width' => '',
		 				'class' => '',
		 				'id' => '',
		 			),
		 			'return_format' => 'array',
		 		),
		 	),
		 ),
		array(
			'key' => 'field_60ff052d8e5b6',
			'label' => 'Banner',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_626c37cd602az',
			'label' => 'Mission or Mass?',
			'name' => 'mass_or_mission',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => 'Mission',
			'ui_off_text' => 'Mass Times',
		),
		array(
			'key' => 'field_60ff053d8e5b7',
			'label' => 'Image',
			'name' => 'banner_image',
			'type' => 'image',
			'instructions' => 'Recommended size 550x450.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_60ff055e8e5b8',
			'label' => 'Title',
			'name' => 'banner_title',
			'type' => 'text',
			'instructions' => 'Max Characters: 20',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Banner title',
			'prepend' => '',
			'append' => '',
			'maxlength' => 20,
		),
		array(
			'key' => 'field_60ff058c8e5b9',
			'label' => 'Content',
			'name' => 'banner_content',
			'type' => 'textarea',
			'instructions' => 'Max Characters: 250',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_626c37cd602az',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => 250,
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_60ff05e98e5ba',
			'label' => 'Link',
			'name' => 'banner_links',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 2,
			'layout' => 'table',
			'button_label' => 'Add Link',
			'sub_fields' => array(
				array(
					'key' => 'field_612fb6b81eabe',
					'label' => 'Banner Link',
					'name' => 'banner_link',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
			),
		),
		array(
			'key' => 'field_5f5a27d7acd8b',
			'label' => 'Featured Buttons',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_61847ce9ce3dz',
			'label' => 'Featured Buttons Title',
			'name' => 'featured_buttons_title',
			'type' => 'text',
			'instructions' => 'Character limit 50.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => 50,
		),
		array(
			'key' => 'field_5f5a27feacd8c',
			'label' => 'Featured Buttons',
			'name' => 'featured_buttons',
			'type' => 'repeater',
			'instructions' => 'These buttons will display just below the Hero.<br />*Max: 8',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_60ff03abcbe83',
			'min' => 2,
			'max' => 8,
			'layout' => 'block',
			'button_label' => 'Add Featured Button',
			'sub_fields' => array(
				array(
					'key' => 'field_60ff0354cbe82',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_60ff03abcbe83',
					'label' => 'Link',
					'name' => 'link',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
			),
		),
		array(
			'key' => 'field_61847ccace3db',
			'label' => 'Lower Banner',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_61847cdbce3dc',
			'label' => 'Lower Banner Image',
			'name' => 'lower_banner_image',
			'type' => 'image',
			'instructions' => 'Recommended size 500x400.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_61847ce9ce3dd',
			'label' => 'Lower Banner Title',
			'name' => 'lower_banner_title',
			'type' => 'text',
			'instructions' => 'Max Characters: 50',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => 50,
		),
		array(
			'key' => 'field_61847cf3ce3de',
			'label' => 'Lower Banner Description',
			'name' => 'lower_banner_description',
			'type' => 'textarea',
			'instructions' => 'Max Characters: 200',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => 200,
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_61847d07ce3df',
			'label' => 'Lower Banner Button',
			'name' => 'lower_banner_button',
			'type' => 'link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
		),
		array(
			'key' => 'field_622ea163fea63',
			'label' => 'Social Banner',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_622ea175fea64',
			'label' => 'Jump Off Point?',
			'name' => 'jump_off_point_social',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_622ea18efea65',
			'label' => 'Social Title',
			'name' => 'social_title',
			'type' => 'text',
			'instructions' => 'Max Characters: 30',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => 30,
		),
		array(
			'key' => 'field_622ea196fea66',
			'label' => 'Behaviour on mobile devices',
			'name' => 'featured_content_is_slider_social',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_622ea175fea64',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Slider',
			'ui_off_text' => 'Stack',
		),
		array(
			'key' => 'field_622ea2fefea67',
			'label' => 'Buttons',
			'name' => 'social_buttons',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_622ea175fea64',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 3,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_622ea30dfea68',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => 'Recommended aspect ratio 370 / 305.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_622ea318fea69',
					'label' => 'Title',
					'name' => 'title',
					'type' => 'text',
					'instructions' => 'Max Characters: 50',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => 50,
				),
				array(
					'key' => 'field_622ea323fea6a',
					'label' => 'Text',
					'name' => 'text',
					'type' => 'text',
					'instructions' => 'Max Characters: 200',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => 200,
				),
				array(
					'key' => 'field_622ea328fea6b',
					'label' => 'Link',
					'name' => 'link',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
			),
		),
		array(
			'key' => 'field_622ea3d398262',
			'label' => 'Envira Gallery Shortcode',
			'name' => 'instagram_id',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_622ea175fea64',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_622ea3e798263',
			'label' => 'Social Links',
			'name' => 'social_links',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_622ea175fea64',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_622ea3f698264',
					'label' => 'Icon',
					'name' => 'icon',
					'type' => 'font-awesome',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'icon_sets' => array(
						0 => 'fas',
						1 => 'far',
						2 => 'fab',
					),
					'custom_icon_set' => '',
					'default_label' => '',
					'default_value' => '',
					'save_format' => 'element',
					'allow_null' => 0,
					'show_preview' => 1,
					'enqueue_fa' => 0,
					'fa_live_preview' => '',
					'choices' => array(
					),
				),
				array(
					'key' => 'field_622ea41298265',
					'label' => 'Link',
					'name' => 'link',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
			),
		),
		array(
			'key' => 'field_61847d1ece3e0',
			'label' => 'Calendar',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_61847d2fce3e2',
			'label' => 'Calendar Title',
			'name' => 'calendar_title',
			'type' => 'text',
			'instructions' => 'Max Characters: 30',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => 30,
		),
		array(
			'key' => 'field_61847d35ce3e3',
			'label' => 'Calendar Link',
			'name' => 'calendar_link',
			'type' => 'link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
		),
		array(
			'key' => 'field_61847d27ce3e1',
			'label' => 'Calendar Shortcode',
			'name' => 'calendar_shortcode',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6184bdf32b5fc',
			'label' => 'Calendar Background Image',
			'name' => 'calendar_background_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'templates/page-cluster.php',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Settings for Cluster Template',
));

endif;
